export const LIST_ART_START = "LIST_ALL_START";
export const LIST_ART_SUCCESS = "LIST_ALL_SUCCESS";
export const LIST_ART_FAIL = "LIST_ALL_FAIL";
export const CHANGE_PAGE = "CHANGE_PAGE";

export const GET_ART_DETAIL_START = "GET_ART_DETAIL_START";
export const GET_ART_DETAIL_SUCCESS = "GET_ART_DETAIL_SUCCESS";
export const GET_ART_DETAIL_FAIL = "GET_ART_DETAIL_FAIL";
